#!/bin/bash
#
# Updates android-studio-kotlin-versions.properties with current Android Studio releases.
#
# Uses the same policy as the TeamCity "Plugin for IDE, Trigger" build:
#   1. Fetches Android Studio releases from Google's updates.xml
#   2. Extracts IntelliJ platform build numbers from apiVersion attributes
#   3. Looks up real Kotlin compiler version from JetBrains VCS model.properties
#
# Requires:
#   SPACE_TOKEN - JetBrains Space VCS access token
#                 (same as TeamCity's %space.intellij.token% or PERSONAL_SPACE_PASSWORD)
#
# Usage:
#   SPACE_TOKEN=<token> ./scripts/update-android-studio-versions.sh
#   SPACE_TOKEN=$PERSONAL_SPACE_PASSWORD ./scripts/update-android-studio-versions.sh

set -e

if [[ -z "$SPACE_TOKEN" ]]; then
    if [[ -n "$PERSONAL_SPACE_PASSWORD" ]]; then
        SPACE_TOKEN="$PERSONAL_SPACE_PASSWORD"
    else
        echo "Error: SPACE_TOKEN environment variable is required"
        echo "This is the JetBrains Space VCS access token (same as TeamCity's %space.intellij.token%)"
        echo "Alternatively, set PERSONAL_SPACE_PASSWORD"
        exit 1
    fi
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="$PROJECT_DIR/src/main/resources/android-studio-kotlin-versions.properties"

MINIMUM_VERSION="243.21565.193"

echo "Fetching Android Studio releases..."
as_xml=$(curl -s -f https://dl.google.com/android/studio/patches/updates.xml)

if [[ -z "$as_xml" ]]; then
    echo "Error: Failed to fetch Android Studio updates.xml"
    exit 1
fi

# Extract apiVersion attributes from all channels, strip AI- prefix, deduplicate
echo "Extracting platform build numbers..."
platform_builds=""

for channel in AI-1-release AI-1-beta AI-1-eap; do
    case "$channel" in
        AI-1-release) limit=15 ;;
        *)            limit=3 ;;
    esac

    all_channel_builds=$(echo "$as_xml" | \
        xmllint --xpath "/products/product/channel[@id='$channel']/build/@apiVersion" - 2>/dev/null | \
        sed -En 's/ ?apiVersion="AI-([^"]*)"/\1\n/gp' | \
        sed '/^$/d' | \
        head -$limit)

    channel_builds=$(echo "$all_channel_builds" | sed '/^$/d' | sort -u -t '.' -k1,1n -k2,2n -k3,3n)

    if [[ -n "$channel_builds" ]]; then
        all_count=$(echo "$all_channel_builds" | wc -l | tr -d ' ')
        unique_count=$(echo "$channel_builds" | wc -l | tr -d ' ')
        echo "  $channel: $all_count builds, $unique_count unique (limit $limit)"
        echo "    all:    $(echo "$all_channel_builds" | tr '\n' ' ')"
        echo "    unique: $(echo "$channel_builds" | tr '\n' ' ')"
        platform_builds+="$channel_builds"$'\n'
    else
        echo "  $channel: no builds found"
    fi
done

# Deduplicate across channels
platform_builds=$(echo "$platform_builds" | sed '/^$/d' | sort -u -t '.' -k1,1n -k2,2n -k3,3n)

if [[ -z "$platform_builds" ]]; then
    echo "Error: No platform builds found in updates.xml"
    exit 1
fi

echo ""
echo "Unique platform builds:"
echo "$platform_builds"

# Filter by minimum version
min_maj=$(echo "$MINIMUM_VERSION" | cut -d. -f1)
min_min=$(echo "$MINIMUM_VERSION" | cut -d. -f2)
min_patch=$(echo "$MINIMUM_VERSION" | cut -d. -f3)

filtered_builds=""
while IFS= read -r build; do
    if [[ -z "$build" ]]; then continue; fi

    b_maj=$(echo "$build" | cut -d. -f1)
    b_min=$(echo "$build" | cut -d. -f2)
    b_patch=$(echo "$build" | cut -d. -f3)

    if (( b_maj > min_maj )) || \
       (( b_maj == min_maj && b_min > min_min )) || \
       (( b_maj == min_maj && b_min == min_min && b_patch >= min_patch )); then
        filtered_builds+="$build"$'\n'
    fi
done <<< "$platform_builds"

filtered_builds=$(echo "$filtered_builds" | sed '/^$/d' | sort -u -t '.' -k1,1n -k2,2n -k3,3n)

echo ""
echo "Filtered builds (>= $MINIMUM_VERSION):"
echo "$filtered_builds"
echo ""

# Write header
cat > "$OUTPUT_FILE" << 'HEADER'
# Maps IntelliJ platform build number to real Kotlin compiler version
# for Android Studio, which uses stub versions (X.Y.255-dev-Z) in compiler.version.
#
# Generated by scripts/update-android-studio-versions.sh
#
# Platform build is extracted from the AS build number:
#   AI-PPP.NNNNN.NN.XXXX.YYYYYYYY -> PPP.NNNNN.NN
#
# The real Kotlin version is determined from:
#   idea/<platform-build>/community/plugins/kotlin/.../model.properties -> kotlincVersion
HEADER

# For each platform build, fetch kotlincVersion from model.properties
while IFS= read -r build; do
    if [[ -z "$build" ]]; then continue; fi

    echo "Looking up Kotlin version for platform build $build..."

    kotlin_version=$(curl -s -f \
        "https://jetbrains.team/vcs/file/IJ/ultimate/refs/tags/idea/$build/community/plugins/kotlin/util/project-model-updater/resources/model.properties" \
        -H "Authorization: Bearer $SPACE_TOKEN" 2>/dev/null | \
        sed -En 's/.*kotlincVersion=(.*)/\1/p' | \
        tr -d '[:space:]')

    if [[ -n "$kotlin_version" ]]; then
        echo "  $build -> $kotlin_version"
        echo "$build=$kotlin_version" >> "$OUTPUT_FILE"
    else
        echo "  $build -> NOT FOUND (tag may not exist)"
    fi
done <<< "$filtered_builds"

echo ""
echo "Updated: $OUTPUT_FILE"
echo ""
echo "Contents:"
cat "$OUTPUT_FILE"
